### PR TITLE
Add the PageView reverse parameter

### PR DESCRIPTION
**Pull request by nvbln**
Implements the PageView reverse parameter, saves having to reverse the given data.

### CODE REVIEW

**Comment by renancaraujo** [comment]
Looks good, just run `flutter format .` on the project to solve format errors.

**Comment by nvbln** [comment]
That's where things get interesting, as running `flutter format .` leaves everything unchanged..

**Comment by renancaraujo** [comment]
Holy shmoly, LGTM then (I will check this. travis issue later).

**Comment by renancaraujo** [comment]
lgtm

**Pull request merged**
