### PR TITLE
Enabling rotation gesture

### PR DESCRIPTION
**Pull request by renancaraujo**

### CODE REVIEW

**Comment by suhas4090** [comment]
when will the rotation and move image will be implemented

**Comment by suhas4090** [comment]
i am using files of 
https://github.com/renancaraujo/photo_view/tree/4bf597fdee1e46fd3b4aab22159f73557948c4f9

where i modified some files to move image position as well.

the custom library RotateGestureDetector was very helpful. Thanks. 👍

**Comment by renancaraujo** [comment]
I've opened a [PR in flutter/flutter ](https://github.com/flutter/flutter/pull/17345) adding framework support for rotation gesture. I've opened as I wait for final disclosure of this question since I think that a `GestureDetector` is a huge responsibility to carry with Photo View as a lib.  

In other words, this PR is a snapshot of how Photo View must behave when rotation becomes available in Flutter. 

If you think your changes are a good addition, you can share here, that would be great.

**Comment by renancaraujo** [comment]
Unfortunately, I'm not having time to update this branch anymore. Photo View will support rotation as soon as flutter does.

**Pull request closed without merging**
