### PR TITLE
added onLongPress callback

### PR DESCRIPTION
**Pull request by xioxin**

### CODE REVIEW

**Comment by renancaraujo** [comment]
Hello @xioxin, thanks for your contribution.

Before merge I need to underdtand if this is really necessary. 
Cant you listen for long presses with an external gesture detector?

**Comment by xioxin** [comment]
I'm sorry, my English is poor

I need to implement long press pop-up save menu.

Use onTapUp and onTapDown events to judge the time difference. need to release hand to trigger, which is not in line with the usage habits.

**Comment by xioxin** [comment]
Nesting GestureDetector in the outer layer is a better way

**Comment by yangyxd** [comment]
Hi @renancaraujo 
Thank you for providing this plug-in.

Now I use the latest flitter dev branch. Gesturedetector can't trigger onLongPress on the mobile phone, but it can on the simulator. I don't know why and how to solve it?

**Comment by SeakyLuo** [comment]
> Hello @xioxin, thanks for your contribution.
> 
> Before merge I need to underdtand if this is really necessary. Cant you listen for long presses with an external gesture detector?

Why is this not necessary when you need to add this long press listener anyway? Adding it would make this implementation much easier. 

Sorry, I don't see the reason why it is more reasonable to add an external gesture detector than giving each page a detector.

**Pull request closed without merging**
