### PR TITLE
Allow programmatic rotate when PhotoView enableRotation is disabled

### PR DESCRIPTION
**Pull request by scopendo**
Allows the photo view to be rotated by setting the `PhotoViewController.rotation` property even when the photo view's `enableRotation` property is not enabled.

Relates to issue #257.

### CODE REVIEW

**Comment by scopendo** [comment]
Pull request updated with an example.  This PR now allows programmatic rotation of the photo view when gesture-based rotation is disabled, meaning that `enableRotation` is false.

The PR also includes a follow-on fix for preventing rotation value being updated in the output stream by manual rotation gestures, when `enableRotation` is false.

**Comment by scopendo** [comment]
Updated to fix an issue whereby scaling after programmatic rotation reverted the (custom) child back to the original rotation.  In so doing the fix is much simpler, avoiding sub-classing PhotoViewControllerValue.

In essence, the fix is to allows apply the rotation to the transform, ensuring however that manual rotation gestures do not update the internal rotation state.

**Comment by renancaraujo** [comment]
Gonna hold this merge since it is a breaking change, sorry for that.

**Comment by 120011676** [comment]
It feels like sometimes you need to disable gestures and allow programming

**Comment by renancaraujo** [comment]
Tried to rebase by myself and messed up your branch pretty hard. 
Opening a new PR and adding you as co-author.

**Pull request closed without merging**
